Dockerfile: stop copying endorser
When building container from scratch with `make docker-image` on master
branch, it gives me this error:

```
[3/3] STEP 1/12: FROM
registry.gitlab.com/tezos/opam-repository:runtime-dependencies--4aabc02a9c160ecae2a39153c27c0a67000a999b
AS debug
Error: error building at STEP "COPY --chown=tezos:nogroup --from=builder
/home/tezos/tezos/tezos-endorser-* /home/tezos/bin/": checking on
sources under
"/home/nochem/.local/share/containers/storage/overlay/3a141d5c305922e01a1a99620f6e37675510cdff2d074274e5e998527c8af033/merged":
Rel: can't make  relative to
/home/nochem/.local/share/containers/storage/overlay/3a141d5c305922e01a1a99620f6e37675510cdff2d074274e5e998527c8af033/merged;
copier: stat: ["/home/tezos/tezos/tezos-endorser-*"]: no such file or
directory
make: *** [Makefile:333: docker-image-debug] Error 125
```

Endorser is no longer getting built in any of the official protos, so
this COPY line must go.