Nix: Disable "zerocallusedregs"
It causes problems when building kernels for the WASM PVM.

```
error: unsupported option '-fzero-call-used-regs=used-gpr' for target 'wasm32-unknown-unknown'
```