Context: fix documentation error
Error message:
```
File "src/lib_context/sigs/context.ml", line 813, characters 27-43:
Error: '{produce,verify}': bad markup.
Suggestion: did you mean '{!produce,verify}' or '[produce,verify]'?
```

Error:
The form `{foo,bar}` used in this comment is inspired by shell-globing.
But it is incompatible with ocamldoc. It just needed to be rewritten to
not use this form.

Also, it wasn't using `[...]` to indicate code which is now fixed.