Proto-alpha: fix documentation error
Error message:
```
File "src/proto_alpha/lib_protocol/dal_slot_index_repr.mli", line 71, characters 6-12:
Error: '{None}': bad markup.
Suggestion: did you mean '{!None}' or '[None]'?
```

Error:
This seem to be a mixup between `{!None}` (a reference to the
constructor `None`) and `[None]` (a code-formatted string "None").
Either of the forms are ok. The reference seems unnecessary because
`None` is an integral part of the Stdlib.