Etherlink/LWR: add farfadet dependency
To avoid:
```
error: failed to select a version for `alloy-primitives`.
    ... required by package `revm-primitives v21.0.2`
    ... which satisfies dependency `primitives = "^21.0.2"` of package `revm v33.1.0`
    ... which satisfies dependency `revm = "^33.1.0"` of package `evm_kernel_farfadet v0.1.0 (/home/rodi/tezos/tezos/etherlink/kernel_farfadet/kernel)`
    ... which satisfies path dependency `kernel-farfadet` of package `octez-evm-node-wasm-runtime v0.0.0-dev (/home/rodi/tezos/tezos/etherlink/lib_wasm_runtime)`
versions that meet the requirements `^1.3.1` are: 1.4.1, 1.4.0, 1.3.1

all possible versions conflict with previously selected packages.

  previously selected package `alloy-primitives v1.3.0`
    ... which satisfies dependency `alloy-primitives = "=1.3.0"` of package `evm-execution-ebisu v0.1.0 (/home/rodi/tezos/tezos/etherlink/kernel_ebisu/evm_execution)`
    ... which satisfies path dependency `evm-execution` (locked to 0.1.0) of package `evm_kernel_ebisu v0.1.0 (/home/rodi/tezos/tezos/etherlink/kernel_ebisu/kernel)`
    ... which satisfies path dependency `kernel-ebisu` (locked to 0.1.0) of package `octez-evm-node-wasm-runtime v0.0.0-dev (/home/rodi/tezos/tezos/etherlink/lib_wasm_runtime)`
```
it was required to ping the version of alloy's crates to at least `1.3.1`.