Proto-alpha: fix documentation error
Error message:
```
File "src/proto_alpha/lib_protocol/sc_rollup_repr.mli", line 80, characters 31-31:
Error: Identifier in reference should not be empty.
```

Error:
The docstring included the form `{!Module_name.}` which is a reference
(`{!...}`) but to an invalid identifier: a module name with a dot
without a following identifier.