bump dependency lower-bounds in opam file
Job checking the lower bounds:
https://ci.ocamllabs.io/gitlab/nomadic-labs/data-encoding/commit/516dc4518bab7f93f46ff1777f538ea9c872256a/variant/%28lint-lower-bounds%29

Output (excerpt):
The following actions will be performed:
  - install conf-gmp                1
  - install conf-m4                 1
  - install jbuilder                1.0+beta20.1
  - install result                  1.0
  - install ocamlbuild              0.14.0
  - install dune                    2.0.1
  - install conf-perl               1
  - install conf-which              1
  - install ocamlfind               1.8.1
  - install ppx_derivers            1.0
  - install ocaml-compiler-libs     v0.11.0
  - install bigstringaf             0.1.0
  - install uchar                   0.0.2
  - install zarith_stubs_js         v0.12.0
  - install sexplib0                v0.13.0
  - install seq                     0.2.2
  - install either                  1.0.0
  - install dune-private-libs       2.0.1
  - install zarith                  1.4
  - install topkg                   0.8.1
  - install num                     1.0
  - install easy-format             1.0.1
  - install base-bytes              base
  - install ocaml-migrate-parsetree 1.5.0
  - install re                      1.8.0
  - install dune-configurator       2.0.1
  - install cmdliner                1.0.0
  - install afl-persistent          1.1
  - install biniou                  1.2.0
  - install stringext               1.4.0
  - install omd                     1.3.1
  - install cppo                    1.6.1
  - install astring                 0.8.2
  - install ppx_tools_versioned     5.2.3
  - install base                    v0.13.1
  - install uutf                    1.0.1
  - install fmt                     0.8.0
  - install md2mld                  0.2.0
  - install yojson                  1.5.0
  - install ocplib-endian           1.0
  - install variantslib             v0.13.0
  - install stdio                   v0.13.0
  - install parsexp                 v0.13.0
  - install fieldslib               v0.13.0
  - install jsonm                   1.0.1
  - install alcotest                0.8.0
  - install js_of_ocaml-compiler    3.5.2
  - install crowbar                 0.2
  - install ppxlib                  0.12.0
  - install sexplib                 v0.13.0
  - install js_of_ocaml             3.5.2
  - install ppx_variants_conv       v0.13.0
  - install ppx_sexp_conv           v0.13.0
  - install ppx_inline_test         v0.13.0
  - install ppx_here                v0.13.0
  - install ppx_fields_conv         v0.13.0
  - install ppx_compare             v0.13.0
  - install ppx_cold                v0.13.0
  - install cstruct                 3.0.0
  - install uri                     1.9.5
  - install ppx_custom_printf       v0.13.0
  - install ppx_hash                v0.13.0
  - install ppx_assert              v0.13.0
  - install hex                     1.3.0
  - install ppx_expect              v0.13.0
  - install ezjsonm                 0.5.0

[…]

      ocamlc src/.data_encoding.objs/byte/data_encoding__Binary_slicer.{cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "src/binary_slicer.ml", line 306, characters 41-62:
306 |       ~pp:(fun b -> Format.sprintf "%S" (Bigstringaf.to_string b))
                                               ^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Bigstringaf.to_string
Hint: Did you mean of_string?
    ocamlopt src/.data_encoding.objs/native/data_encoding__Binary_slicer.{cmx,o} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlopt.opt […])
File "src/binary_slicer.ml", line 306, characters 41-62:
306 |       ~pp:(fun b -> Format.sprintf "%S" (Bigstringaf.to_string b))
                                               ^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Bigstringaf.to_string
Hint: Did you mean of_string?
      ocamlc src/.data_encoding.objs/byte/data_encoding__Binary_writer.{cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "src/binary_writer.ml", line 227, characters 4-29:
227 |     Bigstringaf.blit_to_bytes s ~src_off:0 state.buffer ~dst_off:ofs ~len:length
          ^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Bigstringaf.blit_to_bytes
    ocamlopt src/.data_encoding.objs/native/data_encoding__Binary_writer.{cmx,o} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlopt.opt […])
File "src/binary_writer.ml", line 227, characters 4-29:
227 |     Bigstringaf.blit_to_bytes s ~src_off:0 state.buffer ~dst_off:ofs ~len:length
          ^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Bigstringaf.blit_to_bytes
    ocamlopt src/.data_encoding.objs/native/data_encoding__Binary_stream_reader.{cmx,o} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlopt.opt […])
File "src/binary_stream_reader.ml", line 286, characters 4-31:
286 |     Bigstringaf.blit_from_bytes buf ~src_off:ofs b ~dst_off:0 ~len:length ;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Bigstringaf.blit_from_bytes
      ocamlc src/.data_encoding.objs/byte/data_encoding__Binary_stream_reader.{cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "src/binary_stream_reader.ml", line 286, characters 4-31:
286 |     Bigstringaf.blit_from_bytes buf ~src_off:ofs b ~dst_off:0 ~len:length ;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Bigstringaf.blit_from_bytes
    ocamlopt src/.data_encoding.objs/native/data_encoding__Binary_length.{cmx,o}
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Z, and its interface was not compiled with -opaque
    ocamlopt src/.data_encoding.objs/native/data_encoding__Binary_reader.{cmx,o}
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Z, and its interface was not compiled with -opaque
      ocamlc src/.data_encoding.objs/byte/data_encoding__Json.{cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "src/json.ml", line 322, characters 14-35:
322 |               Bigstringaf.to_string
                    ^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Bigstringaf.to_string
Hint: Did you mean of_string?
    ocamlopt src/.data_encoding.objs/native/data_encoding__Json.{cmx,o} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlopt.opt […])
File "src/json.ml", line 322, characters 14-35:
322 |               Bigstringaf.to_string
                    ^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Bigstringaf.to_string
Hint: Did you mean of_string?
      ocamlc src/.data_encoding.objs/byte/data_encoding__V1.{cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "src/v1.ml", line 185, characters 14-35:
185 |               Bigstringaf.to_string s)
                    ^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Bigstringaf.to_string
Hint: Did you mean of_string?
    ocamlopt src/.data_encoding.objs/native/data_encoding__V1.{cmx,o} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlopt.opt […])
File "src/v1.ml", line 185, characters 14-35:
185 |               Bigstringaf.to_string s)
                    ^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Bigstringaf.to_string
Hint: Did you mean of_string?
      ocamlc test/.test.eobjs/byte/dune__exe__Guarded_conv.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "test/guarded_conv.ml", line 62, characters 10-22:
62 |   assert (Result.is_ok s) ;
               ^^^^^^^^^^^^
Error: Unbound value Result.is_ok
      ocamlc test/.test.eobjs/byte/dune__exe__Guarded_decode.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "test/guarded_decode.ml", line 60, characters 10-22:
60 |   assert (Result.is_ok s) ;
               ^^^^^^^^^^^^
Error: Unbound value Result.is_ok
      ocamlc test/.test.eobjs/byte/dune__exe__Helpers.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "test/helpers.ml", line 57, characters 6-20:
57 |       Alcotest.failf
           ^^^^^^^^^^^^^^
Error: Unbound value Alcotest.failf
Hint: Did you mean fail?
      ocamlc test/.test.eobjs/byte/dune__exe__Registrationed.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "test/registrationed.ml", line 40, characters 12-26:
40 |   | None -> Alcotest.failf "Could not find %s" id
                 ^^^^^^^^^^^^^^
Error: Unbound value Alcotest.failf
Hint: Did you mean fail?
      ocamlc test/.test.eobjs/byte/dune__exe__Slice_test.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "test/slice_test.ml", line 296, characters 11-25:
296 |       else Alcotest.failf "Unexpected slicintg result %s /= %s" pretty_printed r
                 ^^^^^^^^^^^^^^
Error: Unbound value Alcotest.failf
Hint: Did you mean fail?
      ocamlc test/expect/.data_encoding_expect_tests.objs/byte/data_encoding_expect_tests__Bigstr.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "test/expect/bigstr.ml", line 30, characters 12-35:
30 |   let res = Ezjsonm.value_to_string json in
                 ^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Ezjsonm.value_to_string
      ocamlc test/expect/.data_encoding_expect_tests.objs/byte/data_encoding_expect_tests__Stringbytes.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "test/expect/stringbytes.ml", line 30, characters 12-35:
30 |   let res = Ezjsonm.value_to_string json in
                 ^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Ezjsonm.value_to_string
    ocamlopt src/.data_encoding.objs/native/data_encoding__Encoding.{cmx,o}
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Z, and its interface was not compiled with -opaque
      ocamlc test/.test.eobjs/byte/dune__exe__Write_failure.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "test/write_failure.ml", line 35, characters 6-20:
35 |       Alcotest.failf "Unexpected exception: %s." (Printexc.to_string exn)
           ^^^^^^^^^^^^^^
Error: Unbound value Alcotest.failf
Hint: Did you mean fail?
    ocamlopt test/.test.eobjs/native/dune__exe__Uint_like_n.{cmx,o}
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Z, and its interface was not compiled with -opaque
    ocamlopt test/.test.eobjs/native/dune__exe__Int_like_z.{cmx,o}
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Z, and its interface was not compiled with -opaque
      ocamlc test/pbt/.test_generated.eobjs/byte/dune__exe__Generators.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt […])
File "test/pbt/generators.ml", line 792, characters 9-27:
792 |       && Bigstringaf.memcmp a 0 b 0 (Bigstringaf.length a) = 0
               ^^^^^^^^^^^^^^^^^^
Error: Unbound value Bigstringaf.memcmp
    ocamlopt test/.test.eobjs/native/dune__exe__Types.{cmx,o}
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Z, and its interface was not compiled with -opaque
    ocamlopt test/expect/.data_encoding_expect_tests.objs/native/data_encoding_expect_tests__Base.{cmx,o}
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Z, and its interface was not compiled with -opaque