Lazy-containers: fix broken doc
Error message:
```
File "src/lib_lazy_containers/lazy_vector.mli", line 185, characters 13-14:
Error: End of text is not allowed in '{b ...}' (boldface text).
File "tezos_lazy_containers__Lazy_vector.cmti":
```

Error:
The `{b ...}` markup was missing its closing `}`.