Crypto-dal: fix documentation formatting
Error message:
```
File "src/lib_crypto_dal/cryptobox_intf.ml", line 71, characters 37-50:
Error: Reference to 'parameters' is ambiguous. Please specify its kind: type-parameters, val-parameters.
```

Error:
Ambiguous identifier. The kind of identifier needed to be specified.