CI/Cache: use job cache instead of pipeline cache in [oc.script:snapshot_alpha_and_link]
The cache pipeline is not available when this job runs in a pipeline:
https://gitlab.com/tezos/tezos/-/jobs/12380632320#L61

Exception: when it is retried
e.g. in pipeline https://gitlab.com/tezos/tezos/-/pipelines/2210576894
first try: no dune cache: https://gitlab.com/tezos/tezos/-/jobs/12412657581#L55
second try: some dune cache: https://gitlab.com/tezos/tezos/-/jobs/12412743352