Benchmarks: fix documentation errors
Error message:
```
File "src/lib_benchmark/maths.mli", line 32, characters 4-6:
Error: '{R' should be followed by space, a tab, or a new line.
File "src/lib_benchmark/maths.mli", line 32, characters 4-15:
Error: '{R ...}' (right alignment) should not be used because it has no effect.
File "src/lib_benchmark/maths.mli", line 35, characters 4-16:
Error: '{Write-only}': bad markup.
Suggestion: did you mean '{!Write-only}' or '[Write-only]'?
```

Error:
The comment had `{Read-only}` and `{Write-only}` which are both invalid.
I used `{e ...}` (for emphasis) assuming that the delimiters were added
for something along those lines.