Stdlib: fix documentation issue
Error message:
```
File "src/lib_stdlib/tzString.mli", line 54, characters 8-11:
Error: '{li ...}' (list item) is not allowed in '{li ...}' (list item).
Suggestion: move '{li ...}' into '{ul ...}' (bulleted list), or use '-' (bulleted list item).
```

Error:
The `{li ...}` block was missing its closing `}`.